version: '3.8'

services:
<<<<<<< HEAD
  # 1. 데이터베이스
=======
>>>>>>> ca88073 (feat: AI 발주 제안 페이지 데이터 연동 및 현재고/분석사유 추가)
  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
<<<<<<< HEAD
      - TZ=Asia/Seoul
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=my_database
      - MYSQL_INITCONF=--default-time-zone=+09:00
    ports:
      - "3306:3306"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./mysql_data:/var/lib/mysql
    networks:
      - app-network

  # 2. 백엔드 (FastAPI)
=======
      TZ: "Asia/Seoul"
      MYSQL_ROOT_PASSWORD: "root_password"
      MYSQL_DATABASE: "my_database"
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

>>>>>>> ca88073 (feat: AI 발주 제안 페이지 데이터 연동 및 현재고/분석사유 추가)
  backend:
    build: ./backend
    container_name: fastapi-backend
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - app-network
    environment:
<<<<<<< HEAD
      - TZ=Asia/Seoul  
    volumes:
      - /etc/localtime:/etc/localtime:ro

  # 3. 프론트엔드 (React)
=======
      TZ: "Asia/Seoul"
      DATABASE_URL: "mysql+pymysql://root:root_password@db:3306/my_database"
    volumes:
      - ./backend:/app

>>>>>>> ca88073 (feat: AI 발주 제안 페이지 데이터 연동 및 현재고/분석사유 추가)
  frontend:
    build: ./frontend
    container_name: react-frontend
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
<<<<<<< HEAD
    driver: bridge
=======
    driver: bridge

volumes:
  mysql_data:
>>>>>>> ca88073 (feat: AI 발주 제안 페이지 데이터 연동 및 현재고/분석사유 추가)
